version: '3.7'

services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password

  # Serviço do WordPress
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./vime:/var/www/html/wp-content/plugins/vime
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your_database_user
      WORDPRESS_DB_PASSWORD: your_database_password
      WORDPRESS_DB_NAME: your_database_name

volumes:
  db_data:
